In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('./sleep_health_lifestyle_dataset.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 13 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Person ID                              400 non-null    int64
 1   Gender                                 400 non-null    object
 2   Age                                    400 non-null    int64
 3   Occupation                             400 non-null    object
 4   Sleep Duration (hours)                 400 non-null    float64
 5   Quality of Sleep (scale: 1-10)         400 non-null    float64
 6   Physical Activity Level (minutes/day)  400 non-null    int64
 7   Stress Level (scale: 1-10)             400 non-null    int64
 8   BMI Category                           400 non-null    object
 9   Blood Pressure (systolic/diastolic)    400 non-null    object
 10  Heart Rate (bpm)                       400 non-null    int64
 11  Daily Steps                            400 non-null    int64
 12  Sleep Disorder                         110 non-null    object
dtypes: float64(2), int64(6), object(5)
memory usage: 40.8+ KB

In [4]:
# 수면 장애가 있는 데이터
df_with_disorder = df[df['Sleep Disorder'].notna()]

# 수면 장애가 없는 데이터
df_without_disorder = df[df['Sleep Disorder'].isna()]

In [5]:
df_with_disorder.info()
df_with_disorder.head()

<class 'pandas.core.frame.DataFrame'>
Index: 110 entries, 4 to 398
Data columns (total 13 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Person ID                              110 non-null    int64
 1   Gender                                 110 non-null    object
 2   Age                                    110 non-null    int64
 3   Occupation                             110 non-null    object
 4   Sleep Duration (hours)                 110 non-null    float64
 5   Quality of Sleep (scale: 1-10)         110 non-null    float64
 6   Physical Activity Level (minutes/day)  110 non-null    int64
 7   Stress Level (scale: 1-10)             110 non-null    int64
 8   BMI Category                           110 non-null    object
 9   Blood Pressure (systolic/diastolic)    110 non-null    object
 10  Heart Rate (bpm)                       110 non-null    int64
 11  Daily Steps                            110 non-null    int64
 12  Sleep Disorder                         110 non-null    object
dtypes: float64(2), int64(6), object(5)
memory usage: 12.0+ KB

,Person ID,Gender,Age,Occupation,Sleep Duration (hours),Quality of Sleep (scale: 1-10),Physical Activity Level (minutes/day),Stress Level (scale: 1-10),BMI Category,Blood Pressure (systolic/diastolic),Heart Rate (bpm),Daily Steps,Sleep Disorder
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia
8,9,Male,25,Manual Labor,11.9,7.2,27,8,Underweight,112/63,99,16397,Sleep Apnea
12,13,Male,54,Office Worker,4.1,6.8,113,9,Obese,137/90,70,15440,Sleep Apnea
18,19,Female,26,Manual Labor,9.2,6.4,93,9,Underweight,113/65,78,9957,Sleep Apnea
19,20,Male,27,Manual Labor,10.6,8.1,94,8,Normal,113/63,58,17796,Insomnia

In [6]:
df_without_disorder.info()
df_without_disorder.head()

<class 'pandas.core.frame.DataFrame'>
Index: 290 entries, 0 to 399
Data columns (total 13 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Person ID                              290 non-null    int64
 1   Gender                                 290 non-null    object
 2   Age                                    290 non-null    int64
 3   Occupation                             290 non-null    object
 4   Sleep Duration (hours)                 290 non-null    float64
 5   Quality of Sleep (scale: 1-10)         290 non-null    float64
 6   Physical Activity Level (minutes/day)  290 non-null    int64
 7   Stress Level (scale: 1-10)             290 non-null    int64
 8   BMI Category                           290 non-null    object
 9   Blood Pressure (systolic/diastolic)    290 non-null    object
 10  Heart Rate (bpm)                       290 non-null    int64
 11  Daily Steps                            290 non-null    int64
 12  Sleep Disorder                         0 non-null      object
dtypes: float64(2), int64(6), object(5)
memory usage: 31.7+ KB

,Person ID,Gender,Age,Occupation,Sleep Duration (hours),Quality of Sleep (scale: 1-10),Physical Activity Level (minutes/day),Stress Level (scale: 1-10),BMI Category,Blood Pressure (systolic/diastolic),Heart Rate (bpm),Daily Steps,Sleep Disorder
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,NaN
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,NaN
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,NaN
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,NaN
5,6,Female,47,Student,6.1,6.9,24,4,Normal,123/60,87,9485,NaN